# CI/CD Pipeline
# dev branch -> staging
# master branch -> internal (Custom Downloads)
# master branch -> live



# Define stages for the CI/CD pipeline
stages:
  - test_build_static
  - deploy

variables:
  CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}:nginx-${CI_COMMIT_SHORT_SHA}
  CONTAINER_NODE_IMAGE: ${CI_REGISTRY_IMAGE}:node-${CI_COMMIT_SHORT_SHA}
  KUBE_CONTEXT: ens-dev-ctx
  DEPLOYENV: dev
  ENVIRONMENT: production
  DOCKER_TLS_CERTDIR: ""

# Template to build static assets
.build-static:
  stage: test_build_static
  image: node:14.17.0

  before_script:
    - cd src/ensembl

  script:
    - echo "test_build_static"
    - echo "Running ${CI_JOB_ID}"

  after_script:
    - echo "Setting env for next job"
    - echo "BUILD_JOB_ID:${CI_JOB_ID}" > build_static.env

  artifacts:
    reports: 
      dotenv: build_static.env 


.push_static:
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:0.5
  stage: deploy
  environment:
    name : wp-hx-dev-ing
  script:
    - echo  "BUILD_JOB ID IN PUSH STATIC:${BUILD_JOB_ID}"

Test_N_Build:
  extends: .build-static

PushStatic:
  extends: .push_static