# The main purpose of this Dockerfile is to test that ensembl-client
# builds and runs correctly in a docker environment.
# You can also use it to build and run ensembl-client instance locally,
# if you prefer that over running Node directly on your machine.

FROM node:24.11.0 AS builder

ARG SOURCE_DIR="./"

RUN mkdir -p /srv/ensembl-client

COPY ${SOURCE_DIR} /srv/ensembl-client/

WORKDIR /srv/ensembl-client/

# to run playwright tests in headless mode
ENV CI=true

RUN npm ci --loglevel warn && \
    npx playwright install chromium --with-deps && \
    npm run test && \
    npm run build


# PRODUCTION IMAGE
FROM node:24.11.0-alpine AS runner

RUN mkdir -p /srv/ensembl-client
WORKDIR /srv/ensembl-client/

ENV NODE_ENV=production
COPY --from=builder /srv/ensembl-client/package* ./
COPY --from=builder /srv/ensembl-client/dist ./dist/

RUN npm ci --only=production --ignore-scripts

EXPOSE 8080
CMD [ "node", "dist/server/server.js" ]
