# PRODUCTION IMAGE
FROM node:20.9.0-alpine

RUN apk add --no-cache git

WORKDIR /srv/ensembl-client/

ENV NODE_ENV=production
COPY package*.json ./
COPY dist ./dist/

RUN npm ci --only=production --ignore-scripts

EXPOSE 8080
CMD [ "node", "dist/server/server.js" ]
