# Template to setup review app
# Create Service, Apply Ingress rules etc
.setup-review-newk8s:
  stage: setup
  image: dockerhub.ebi.ac.uk/ensembl-web/deploy-tools:latest
  before_script:
    - git clone --depth 1 --branch review-on-newk8s https://gitlab.ebi.ac.uk/ensembl-web/ensembl-k8s-manifests.git
    - kubectl create namespace ${CI_COMMIT_REF_SLUG} --dry-run=client -o yaml | kubectl apply -f -
    
  script:
    # Setup Ingress for default backend
    - cd ensembl-k8s-manifests
    - sed -i "s#<HOST>#${CI_COMMIT_REF_SLUG}.review.ensembl.org#g" review-setup/ingress-host.patch.yaml
    - cp review-setup/*.yaml ./
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}
    - kustomize build ./ | kubectl apply -f -
    
    # Deploy nginx & node
    - echo "NGINX & NODE"
    - mv kustomization-ensembl-client.yaml kustomization.yaml
    - kustomize edit set namespace ${CI_COMMIT_REF_SLUG}
    - kustomize build ./ | kubectl apply -f -

    # Setup Ingress for Genome Browser
    - echo "GENOME-BROWSER HI"
    - cp genome-browser/review/hi/*.yaml ./
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}
    - kustomize build ./ | kubectl apply -f -

    - echo "GENOME-BROWSER LO"
    - cp genome-browser/review/lo/*.yaml ./
    - kustomize edit set namesuffix -- -${CI_COMMIT_REF_SLUG}
    - kustomize build ./ | kubectl apply -f -

  after_script:
    - cd ../../
    - rm -rf ensembl-k8s-manifests
