/**
 * See the NOTICE file distributed with this work for additional information
 * regarding copyright ownership.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { FormPanel } from 'src/content/app/tools/vep/types/vepFormConfig';
import type { DisplaySpec } from 'src/content/app/tools/vep/types/vepDisplaySpec';
import type { FilterField } from 'src/content/app/tools/vep/types/vepResultsFilters';

export type VepResultsResponse = {
  metadata: VepResultsResponseMetadata;
  variants: Variant[];
};

export type VepResultsResponseMetadata = {
  pagination: {
    page: number;
    per_page: number;
    total: number;
  };
  // filters applied to the request
  filters?: FilterMetadata;
  // Allele frequency columns present in this result set (related to what was chosen at input).
  available_af_sources?: AfSource[];
  // A list of variant-impact prediction scores available for this job
  available_scores?: string[];
  // The fields the query builder offers and how each is presented
  filter_fields?: FilterField[] | null;
  display_panels: FormPanel[];
  display: DisplaySpec;
};

// Per-filter count of how many records a filter removed (in pipeline order).
export type FilterStat = {
  field: string;
  removed: number;
};

export type FilterMetadata = {
  unfiltered_total: number;
  filtered_total: number;
  stats: FilterStat[];
};

export type AfSource = {
  key: string; // CSQ column name
  source: string; // gnomad_exomes | gnomad_genomes | all_of_us
  population: string;
  label: string;
};

export type Variant = {
  name: string; // This is a string with which user identifies a variant; in a VCF input, this can be a dot if user does not provide a name
  allele_type: string;
  location: {
    region_name: string;
    start: number;
    end: number;
  };
  reference_allele: ReferenceVariantAllele;
  alternative_alleles: AlternativeVariantAllele[];
  // Every distinct annotation payload on this variant, once.
  // The alleles and transcript consequences point into it by index.
  annotation_pool?: Annotation[];
};

export type ReferenceVariantAllele = {
  allele_sequence: string;
};

export type Annotation = {
  plugin: string; // plugin id
  scope: 'allele' | 'transcript';
  data: Record<string, unknown>; // data generated by the plugin
};

export type AlternativeVariantAllele = {
  allele_sequence: string;
  allele_type: string;
  // A secondary line for a structural allele (the symbolic `allele_sequence`,
  // `<DEL>` / `<BND>`): the span in bases for sized SVs ("765 bp") or a breakend's
  // two loci ("2:321681 ↔ 17:198982")
  structural_variant_detail?: string | null;
  predicted_molecular_consequences: PredictedMolecularConsequence[];
  annotations?: Annotation[];
  annotation_refs?: number[];
};

export type PredictedMolecularConsequence =
  PredictedTranscriptConsequence | PredictedIntergenicConsequence;

export type PredictedTranscriptConsequence = {
  feature_type: 'transcript';
  stable_id: string; // transcript stable id, versioned
  gene_stable_id: string; // ideally, versioned; but ultimately, as stored in the vcfs
  gene_symbol: string | null;
  is_canonical: boolean;
  biotype: string;
  strand: 'forward' | 'reverse';
  consequences: string[];
  // MANE (human GRCh38 only)
  is_mane_select?: boolean;
  is_mane_plus_clinical?: boolean;
  mane_select_refseq_id?: string | null;
  // GENCODE primary (human GRCh38 only)
  is_gencode_primary?: boolean;
  // Transcript-scoped plugin output (protein & functional annotations, HGVS,
  // pathogenicity predictions, gene constraint, ...).
  annotations?: Annotation[];
  annotation_refs?: number[];
};

export type HgvsgRepresentation = {
  genomic: string | null;
};

export type PredictedIntergenicConsequence = {
  feature_type: null;
  consequences: string[];
};
